# Generated by Django 4.0.6 on 2023-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_created_at_remove_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/users/img/default.png', null=True, upload_to='static/users/img/avatars/'),
        ),
    ]
