# Generated by Django 4.0.6 on 2022-08-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_todo_tasks_alter_task_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_desc',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
