# Generated by Django 4.0.6 on 2022-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_task_desc_alter_todo_todo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_title',
            field=models.CharField(max_length=50),
        ),
    ]
