# Generated by Django 4.0.6 on 2022-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_todo_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_desc',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
