# Generated by Django 4.0.6 on 2022-09-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_task_desc_alter_task_task_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date_created']},
        ),
    ]
